# source will be downloaded prior to filling in jinja templates
# Example assumes that this folder has setup.py in it
source:
  git_url: ../

package:
  name: metadata-plugin-requirements
{% if GIT_DESCRIBE_NUMBER > '0' %}
  version: {{ GIT_DESCRIBE_TAG[1:] }}.post{{ GIT_DESCRIBE_NUMBER }}
{% else %}
  version: {{ GIT_DESCRIBE_TAG[1:] }}
{% endif %}

requirements:
  build:
    - barcode-scanner
    - flatland-fork
    - jsonschema
    - microdrop-plugin-template
    - microdrop-utility
    - microdrop >=2.0.post49.dev258705497
    - pandas
    - pyyaml
    - path_helpers >=0.2.post4
    - redirect-io
    - wheeler.pygtkhelpers

  run:
    - barcode-scanner
    - flatland-fork
    - jsonschema
    - microdrop-plugin-template
    - microdrop-utility
    - microdrop >=2.0.post49.dev258705497
    - pandas
    - pyyaml
    - path_helpers >=0.2.post4
    - redirect-io
    - wheeler.pygtkhelpers

about:
  home: http://github.com/wheeler-microfluidics/metadata-plugin
  license: GPL
